FROM python:3.12-slim
WORKDIR /src
COPY ./requirements.txt /src
# RUN pip install -r /src/requirements.txt


# VOLUME $(pwd)/src/:/src/bot
# COPY .env /src/
# COPY . /src
# CMD ["python", "bot/bot.py"]