# version: '3.8'

# services:
#   authservice:
#     build:
#       dockerfile: Dockerfile.auth
#       context: .
#     restart: on-failure
#     ports:
#       - '8888:8888'
    
#   bot:
#     build: .
#     restart: always
#     depends_on:
#       - authservice
    
version: '3.8'

services:
  # authservice:
  #   build:
  #     dockerfile: Dockerfile.auth
  #     context: .
  #   restart: on-failure
  #   ports:
  #     - '8888:8888'
  #     - '465:465'
 





    
  auth_service:
    build: ./auth_service
    container_name: auth_service
    working_dir: /src
    volumes:
      - ./auth_service:/src
    command: bash -c "pip install -r ./requirements.txt; python3 main.py;"
    ports:
      - 8888:8888

  bot_service:
    build: ./bot_service
    container_name: bot_service
    working_dir: /src
    volumes:
      - ./bot_service:/src
    command: bash -c "pip install -r ./requirements.txt; python3 bot.py;"














    # restart: always
    # depends_on:
      # - authservice
    # VOLUME $(pwd)/project/:/src/bot
    
    # environment:
    #   - AUTH_URL=http://authservice:8888
