version: '3.8'

services:
  # postgres:
  #   image: postgres:16
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - 
  #   restart: on-failure
  authservice:
    build: .
    restart: on-failure
    ports:
      - '8888:8888'
    
  bot:
    build: .
    # environment:
    #   DB_HOST: postgres
    #   DB_PORT: 5432
    restart: always
    depends_on:
      - authservice
    




      # $(pwd)/project/:/src/bot             /src
      # pgdata:/var/lib/postgresql/data
      # 
# /home/janissca/hackathon/workspace_manager/src